### PR TITLE
Prefix every filter with `sonata_` to avoid conflict

### LINKED ISSUE #299: Conflict with sonata-project/intl-bundle
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.62.1 3.62.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.4 4.1.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.18.0 3.18.0 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.1.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.5.1  1.5.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.15.0 3.15.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.2.0  2.2.0  Lightweight Exporter library
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.24.0 3.24.0 Symfony SonataMediaBundle
sonata-project/user-bundle               4.5.2  4.5.2  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                      v4.4.5  v5.0.5  Symfony Asset Component
symfony/browser-kit                v5.0.5  v5.0.5  Symfony BrowserKit Component
symfony/cache                      v4.4.5  v5.0.5  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.0.1  v2.0.1  Generic abstractions related to caching
symfony/config                     v4.4.5  v5.0.5  Symfony Config Component
symfony/console                    v4.4.5  v5.0.5  Symfony Console Component
symfony/css-selector               v5.0.5  v5.0.5  Symfony CssSelector Component
symfony/debug                      v4.4.5  v4.4.5  Symfony Debug Component
symfony/debug-bundle               v5.0.5  v5.0.5  Symfony DebugBundle
symfony/debug-pack                 v1.0.7  v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection       v4.4.5  v5.0.5  Symfony DependencyInjection Component
symfony/doctrine-bridge            v4.4.5  v5.0.5  Symfony Doctrine Bridge
symfony/dom-crawler                v5.0.5  v5.0.5  Symfony DomCrawler Component
symfony/dotenv                     v5.0.5  v5.0.5  Registers environment variables from a .env file
symfony/error-handler              v4.4.5  v5.0.5  Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.5  v5.0.5  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v2.0.1  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.5  v5.0.5  Symfony ExpressionLanguage Component
symfony/filesystem                 v4.4.5  v5.0.5  Symfony Filesystem Component
symfony/finder                     v4.4.5  v5.0.5  Symfony Finder Component
symfony/flex                       v1.6.2  v1.6.2  Composer plugin for Symfony
symfony/form                       v4.4.5  v5.0.5  Symfony Form Component
symfony/framework-bundle           v4.4.5  v5.0.5  Symfony FrameworkBundle
symfony/http-client                v5.0.5  v5.0.5  Symfony HttpClient component
symfony/http-client-contracts      v2.0.1  v2.0.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.5  v5.0.5  Symfony HttpFoundation Component
symfony/http-kernel                v4.4.5  v5.0.5  Symfony HttpKernel Component
symfony/inflector                  v5.0.5  v5.0.5  Symfony Inflector Component
symfony/intl                       v4.4.5  v5.0.5  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle               v1.14.6 v1.14.6 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.0.5  v5.0.5  Symfony Messenger Component
symfony/mime                       v4.4.5  v5.0.5  A library to manipulate MIME messages
symfony/monolog-bridge             v5.0.5  v5.0.5  Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver           v4.4.5  v5.0.5  Symfony OptionsResolver Component
symfony/phpunit-bridge             v5.0.5  v5.0.5  Symfony PHPUnit Bridge
symfony/process                    v4.4.5  v5.0.5  Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access            v4.4.5  v5.0.5  Symfony PropertyAccess Component
symfony/property-info              v5.0.5  v5.0.5  Symfony Property Info Component
symfony/proxy-manager-bridge       v4.4.5  v5.0.5  Symfony ProxyManager Bridge
symfony/requirements-checker       v1.1.5  v1.1.5  Check Symfony requirements and give recommendations
symfony/routing                    v4.4.5  v5.0.5  Symfony Routing Component
symfony/security                   v4.4.5  v4.4.5  Symfony Security Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.5  v5.0.5  Symfony SecurityBundle
symfony/serializer                 v5.0.5  v5.0.5  Symfony Serializer Component
symfony/service-contracts          v2.0.1  v2.0.1  Generic abstractions related to writing services
symfony/stopwatch                  v5.0.5  v5.0.5  Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.4.5  v5.0.5  Symfony Templating Component
symfony/translation                v4.4.5  v5.0.5  Symfony Translation Component
symfony/translation-contracts      v2.0.1  v2.0.1  Generic abstractions related to translation
symfony/twig-bridge                v4.4.5  v5.0.5  Symfony Twig Bridge
symfony/twig-bundle                v4.4.5  v5.0.5  Symfony TwigBundle
symfony/validator                  v4.4.5  v5.0.5  Symfony Validator Component
symfony/var-dumper                 v5.0.5  v5.0.5  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v5.0.5  v5.0.5  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle        v5.0.5  v5.0.5  Symfony WebProfilerBundle
symfony/web-server-bundle          v4.4.5  v4.4.5  Symfony WebServerBundle
symfony/webpack-encore-bundle      v1.7.3  v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/workflow                   v5.0.5  v5.0.5  Symfony Workflow Component
symfony/yaml                       v4.4.5  v5.0.5  Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.3.11 (cli) (built: Oct 25 2019 02:24:51) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.31.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

## Subject
Twig's function `format_datetime` provided by "sonata-project/intl-bundle" is being replaced by the one provided by "twig/intl-extra", causing exceptions derived by its different signatures.
I found this issue after updating my dependencies, including "sonata-project/admin-bundle".
See sonata-project/SonataAdminBundle#5835.

## Steps to reproduce
```
$ composer require "sonata-project/intl-bundle" "sonata-project/admin-bundle:^3.62.1"
```

```twig
{{ date | format_datetime(pattern, locale, timezone, dateType, timeType) }}
```
## Expected results
The i18n date being printed.

## Actual results
```
Argument 4 passed to Twig\Extra\Intl\IntlExtension::createDateFormatter() must be of the type string, null given, called in /var/www/html/app/vendor/twig/intl-extra/src/IntlExtension.php on line 260 
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because minor.

This might be annoying to have a `sonata_` prefix, but I don't see an other way to be sure to avoid a conflict with either `twigIntl` or another library.

Closes #299.

## Changelog

```markdown
### Added
-`sonata_format_date` filter
-`sonata_format_time` filter
-`sonata_format_datetime` filter
-`sonata_number_format_*` filters
-`sonata_country` filter
-`sonata_locale` filter
-`sonata_language` filter

### Deprecated
-`format_date` filter
-`format_time` filter
-`format_datetime` filter
-`number_format_*` filters
-`country` filter
-`locale` filter
-`language` filter
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
It would be nice to prefix our functions, but also IMO we should deprecate the old methods. To do so, maybe it is easier if you introduce twigRuntime for the new functions, so you dont rely on same implementation, and can add a deprecation message.

File: src/Twig/Extension/DateTimeExtension.php [hunk 1]
```diff
@@ -40,13 +50,18 @@ public function __construct(DateTimeHelper $helper)
...
         return [
-            new TwigFilter('format_date', [$this, 'formatDate'], ['is_safe' => ['html']]),
-            new TwigFilter('format_time', [$this, 'formatTime'], ['is_safe' => ['html']]),
-            new TwigFilter('format_datetime', [$this, 'formatDatetime'], ['is_safe' => ['html']]),
+            new TwigFilter('format_date', [$this, 'formatDate'], ['is_safe' => ['html']]), // NEXT_MAJOR: Remove this line
+            new TwigFilter('sonata_format_date', [$this, 'formatDate'], ['is_safe' => ['html']]),
+            new TwigFilter('format_time', [$this, 'formatTime'], ['is_safe' => ['html']]), // NEXT_MAJOR: Remove this line
+            new TwigFilter('sonata_format_time', [$this, 'formatTime'], ['is_safe' => ['html']]),
+            new TwigFilter('format_datetime', [$this, 'formatDatetime'], ['is_safe' => ['html']]), // NEXT_MAJOR: Remove this line
+            new TwigFilter('sonata_format_datetime', [$this, 'formatDatetime'], ['is_safe' => ['html']]),
```
Comment (jordisala1991) [inline src/Twig/Extension/DateTimeExtension.php]: Those should use the new runtime directly

Comment (VincentLanglet) [reply src/Twig/Extension/DateTimeExtension.php]: Done

File: src/Twig/Extension/DateTimeExtension.php [hunk 2]
```diff
@@ -57,14 +72,20 @@ public function getFilters()
...
-        if (null !== $pattern) {
-            return $this->helper->format($date, $pattern, $locale, $timezone);
-        }
+        @trigger_error(sprintf(
+            'The %s method is deprecated since 2.x and will be removed on 3.0. '.
+            'Use %s::%s instead.',
+            __METHOD__,
+            DateTimeRuntime::class,
+            __METHOD__,
+        ), \E_USER_DEPRECATED);
```
Comment (franmomu) [inline src/Twig/Extension/DateTimeExtension.php]: IMO these messages should encourage the user to use the new `sonata_*` filters instead of runtime class.

**Comment by franmomu** [comment]
To avoid conflict for users installing both `twig/intl-extra` and this bundle we can maybe to add a config parameter to not load the current filters.

**Comment by VincentLanglet** [comment]
> To avoid conflict for users installing both `twig/intl-extra` and this bundle we can maybe to add a config parameter to not load the current filters.

SonataAdmin is using the format_datetime template of SonataIntl when this bundle is used ; which used the sonata_format_datetime twig method. Also people might want to use sometimes one and sometimes another method.

File: src/Twig/Extension/DateTimeExtension.php (hunk 2 above)
Comment (VincentLanglet) [reply src/Twig/Extension/DateTimeExtension.php]: Done

**Review by jordisala1991 — APPROVED** [review]

**Comment by franmomu** [comment]
> > To avoid conflict for users installing both `twig/intl-extra` and this bundle we can maybe to add a config parameter to not load the current filters.
> 
> SonataAdmin is using the format_datetime template of SonataIntl when this bundle is used ; which used the sonata_format_datetime twig method. Also people might want to use sometimes one and sometimes another method.

Not sure if I understand, but what I meant is that this PR provides alternative `sonata_*` filters which is fine, but if someone who has `twig/intl-extra` and this bundle installed wants to use let's say `format_date` from `twig/intl-extra` they cannot if this bundle registers filters after `twig/intl-extra`. Like https://github.com/sonata-project/SonataNewsBundle/pull/591

**Comment by VincentLanglet** [comment]
> Not sure if I understand, but what I meant is that this PR provides alternative `sonata_*` filters which is fine, but if someone who has `twig/intl-extra` and this bundle installed wants to use let's say `format_date` from `twig/intl-extra` they cannot if this bundle registers filters after `twig/intl-extra`. Like [sonata-project/SonataNewsBundle#591](https://github.com/sonata-project/SonataNewsBundle/pull/591)

Currently, if you use both sonata-intl and twig-intl, there is an issue even if you are using none of these methods : If the twig intl is declared after the sonata intl one, the datetime field from sonataAdmin is crashing. 
By adding the prefix, I fix the display of the datetime field for SonataAdmin users.

If the twig intl is declared after the sonata intl one, with this PR it will be possible for the user to have no issue
- format_date will be the twig one
- sonata_format_date won't conflict.

If the sonata intl is declared after the twig intl one, indeed there will still be an issue so far. It will be fixed in next major.

**Comment by jordisala1991** [comment]
What bundles of Sonata make use of this functions? (Only the non deprecated / abandoned)

**Comment by VincentLanglet** [comment]
> What bundles of Sonata make use of this functions? (Only the non deprecated / abandoned)

Only deprecated/abandoned one are using them.

Can we merge this PR, at least as a first step ?

**Comment by jordisala1991** [comment]
if none of the Sonata bundles are using those features. We could even study if this bundle is really needed or we can deprecate it.

But that is another topic, IMO you can merge, yes

**Comment by VincentLanglet** [comment]
> if none of the Sonata bundles are using those features. We could even study if this bundle is really needed or we can deprecate it.

None are using directly those methods. But there are templates used by SonataAdmin (which is the issue I try to solve).

**Comment by core23** [comment]
The last release is broken, because `DateTimeRuntime` is not registered as a service

**Comment by VincentLanglet** [comment]
Can you do the Pr to fix the three runtime ? (Or i'll do later) I m currently on phone ?

**Comment by jordisala1991** [comment]
Would. be nice to have a minimal test setup that catches those basic errors

**Comment by VincentLanglet** [comment]
Found time for https://github.com/sonata-project/SonataIntlBundle/pull/514
