### PR TITLE
Fix `NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given` (fixes #427)

### LINKED ISSUE #427: Strict type checking throws error on formatting Doctrine decimal type as number
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.102.0 3.102.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.6.0   4.6.0   Symfony SonataBlockBundle
sonata-project/cache                     2.1.1   2.1.1   Cache library
sonata-project/doctrine-extensions       1.13.0  1.13.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.34.3  3.34.3  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.7.0   2.7.0   Lightweight Exporter library
sonata-project/form-extensions           1.9.0   1.9.0   Symfony form extensions
sonata-project/intl-bundle               2.10.1  2.10.1  Symfony SonataIntlBundle
sonata-project/translation-bundle        2.8.1   2.8.1   SonataTranslationBundle
sonata-project/twig-extensions           1.6.0   1.6.0   Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.0.0 (cli) (built: Dec  1 2020 03:33:03) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
```

## Subject

When rendering a Doctrine DECIMAL type (PHP type is string) the `NumberHelper::formatDecimal` is called. Eventually a `\NumberFormatter::format` is called which accepts `int | float` only. Since `declare(strict_types=1);` is set PHP throws an error.

Exactly the same issue has been reported and fixed for `NumberHelper::formatCurrency` in the past.

https://github.com/sonata-project/SonataIntlBundle/issues/256

## Steps to reproduce

Try to format Doctrine DECIMAL type as number in for example the configureListFields .

## Actual results

```
TypeError:
NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given

  at /app/vendor/sonata-project/intl-bundle/src/Templating/Helper/NumberHelper.php:225
  at NumberFormatter->format('15.04')
     (/app/vendor/sonata-project/intl-bundle/src/Templating/Helper/NumberHelper.php:225)
  at Sonata\IntlBundle\Templating\Helper\NumberHelper->format('15.04', 1, array(), array(), null, null)
     (/app/vendor/sonata-project/intl-bundle/src/Templating/Helper/NumberHelper.php:114)
  at Sonata\IntlBundle\Templating\Helper\NumberHelper->formatDecimal('15.04', array(), array(), null, null)
     (/app/vendor/sonata-project/intl-bundle/src/Twig/Extension/NumberExtension.php:106)
```

### PR DESCRIPTION
**Pull request by nocive**
## Subject

I am targeting this branch, because this is a patch.

Closes #427.

## Changelog

```markdown
### Fixed
- Fixed `NumberFormatter::format(): Argument #1 ($num) must be of type int|float, string given`.
```

## To do

- [x] Update the tests;

### CODE REVIEW

File: src/Templating/Helper/NumberHelper.php [hunk 1]
```diff
@@ -345,4 +342,21 @@ protected function parseConstantValue($attribute)
...
+
+        if (\is_string($number)) {
+            if (!\is_numeric($number)) {
+                throw new \typeError('Number must be a numeric string')
+            }
+
+            $number = (float) $number;
+        }
+
+        return $number;
```
Comment (VincentLanglet) [inline src/Templating/Helper/NumberHelper.php:360]:
```
if (\is_float($number) || \is_int($number)) {
     return $number;
}
if(\is_numeric($number)) {
     return (float) $number;
}
throw \TypeError(...)
```

`\is_scalar` returns `true` for boolean. And only one TypeError message is enough.

File: src/Templating/Helper/NumberHelper.php [hunk 2]
```diff
@@ -345,4 +342,21 @@ protected function parseConstantValue($attribute)
 
         return \constant($constantName);
     }
+
+    private function parseNumericValue($number)
```
Comment (VincentLanglet) [inline src/Templating/Helper/NumberHelper.php:346]:
```
/** 
 * @param string|int|float $number
 *
 * @return int|float
 **/
```

Comment (nocive) [reply src/Templating/Helper/NumberHelper.php:351]: done

File: src/Templating/Helper/NumberHelper.php (hunk 1 above)
Comment (nocive) [reply src/Templating/Helper/NumberHelper.php]: done

**Comment by nocive** [comment]
It seems this will break `formatSpellout` since spelled out numbers are not considered numeric and `formatSpellout` also makes use of `format()`.

**Comment by VincentLanglet** [comment]
> It seems this will break `formatSpellout()` since spelled out numbers are not considered numeric and `formatSpellout()` also makes use of `format()`.

So it's maybe better to create and use the private methods in the `formatXXX` methods directly.
Might be better to start by the tests to catch those potential errors.

**Comment by nocive** [comment]
@VincentLanglet definitely, I was doing this one with a half a brain while doing other stuff, sorry for the unnecessary noise.
I'll get back to it asap once I can give it full attention :)

**Comment by nocive** [comment]
@VincentLanglet is there anything that needs to happen for workflows to run?

**Comment by VincentLanglet** [comment]
Since its your first pr i need to approve them everytime

**Comment by nocive** [comment]
Fixed an additional issue detected by PHPStan: https://github.com/sonata-project/SonataIntlBundle/pull/430/checks?check_run_id=3240717569

**Comment by nocive** [comment]
@VincentLanglet please approve once again when you can, I hope I got all of them now.

File: src/Templating/Helper/NumberHelper.php [hunk 3]
```diff
@@ -345,4 +346,22 @@ protected function parseConstantValue($attribute)
 
         return \constant($constantName);
     }
+
+    /**
+     * @param string|int|float $number
+     *
+     * @return int|float
+     **/
```
Comment (jordisala1991) [inline src/Templating/Helper/NumberHelper.php:354]: This should be */, you have one * more

File: src/Templating/Helper/NumberHelper.php [hunk 4]
```diff
@@ -345,4 +346,22 @@ protected function parseConstantValue($attribute)
...
+    {
+        if (\is_float($number) || \is_int($number)) {
+            return $number;
+        }
+
+        if (is_numeric($number)) {
+            return (float) $number;
+        }
+
+        throw new \TypeError('Number must be either a float, an integer or a string');
```
Comment (jordisala1991) [inline src/Templating/Helper/NumberHelper.php:365]: `or a numeric string`

File: src/Templating/Helper/NumberHelper.php (hunk 3 above)
Comment (nocive) [reply src/Templating/Helper/NumberHelper.php]: done

File: src/Templating/Helper/NumberHelper.php (hunk 4 above)
Comment (nocive) [reply src/Templating/Helper/NumberHelper.php]: done

**Review by jordisala1991 — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
No need to talk about the private method in the changelog

**Comment by nocive** [comment]
@VincentLanglet PR description updated accordingly.

**Comment by VincentLanglet** [comment]
Thanks
